pub mod curve;

use std::sync::LazyLock;

use serde::{Deserialize, Serialize};
use ts_rs::TS;

use crate::engine::GameTime;
use crate::protocol::{BuildingKind, DAY_MS};
use curve::Curve;

const H: u32 = DAY_MS / 24;
const HOUR: f64 = H as f64;

/// Something a resident has to do. Two kinds, by where the timing lives:
/// an **accruing** need is generated by the passage of time and carries it
/// in `fill`; a **constant** need is imposed by the world and carries it in
/// the curve of whatever serves it, holding a fixed level meanwhile.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, TS)]
#[ts(export)]
pub enum Need {
    /// Being at home. The baseline every other activity has to beat, and
    /// what pulls a resident back when the shift ends and nothing else is
    /// open yet.
    Home,
    Work,
    Rest,
    /// Meals take as long as the hunger owed, up to a sitting: served at
    /// home always, and wherever sells food while it is open.
    Eat,
}

impl Need {
    /// Baseline first, so ties fall to staying put.
    pub const ALL: [Need; 4] = [Need::Home, Need::Work, Need::Rest, Need::Eat];

    /// Obligation gained per millisecond not spent on it. Zero for a
    /// constant need. For `D` hours a day at unit rate this is `D / (24 - D)`.
    pub fn fill(self) -> f64 {
        match self {
            Need::Work | Need::Home => 0.0,
            Need::Rest => 8.0 / 16.0,
            // About 1.2 hours a day, as people actually spend: a sitting is
            // owed ten hours after the last, and lunch out is worth the
            // drive about six hours after breakfast.
            Need::Eat => 0.05,
        }
    }

    /// The most obligation that can pile up, in milliseconds.
    pub fn cap(self) -> f64 {
        match self {
            Need::Work | Need::Home => 24.0 * HOUR,
            Need::Rest => 12.0 * HOUR,
            Need::Eat => 0.5 * HOUR,
        }
    }

    /// Where a fresh bucket starts. A constant need sits at `k * cap` for
    /// good, and `k` is the threshold: the agent works unless something else
    /// is more than this full. Home must beat waiting overnight at work
    /// (`0.5 * shift / 24`, about 0.19) and lose to a morning's commute.
    pub fn initial(self) -> f64 {
        match self {
            Need::Work => 0.5 * self.cap(),
            Need::Home => 0.3 * self.cap(),
            Need::Rest | Need::Eat => 0.0,
        }
    }

    /// Hours a day an accruing need asks for: the referent `fill` was
    /// derived from. Zero for a constant need, which fills time rather than
    /// demanding it.
    fn daily_ms(self) -> f64 {
        let fill = self.fill();
        DAY_MS as f64 * fill / (1.0 + fill)
    }

    /// The best any tap anywhere serves this: greatest rate, least overhead.
    /// What bounds a bucket's score without looking at any building.
    pub fn bounds(self) -> (f64, GameTime) {
        TAPS.iter()
            .flat_map(|(_, taps)| taps.iter())
            .filter(|t| t.need == self)
            .fold((0.0, GameTime::MAX), |(r, h), t| (r.max(t.rate), h.min(t.overhead)))
    }

    /// The most any option for a bucket at `level` can score, from the
    /// bounds alone: `w * min(R, L / H)`.
    pub fn ceiling(self, level: f64) -> f64 {
        let (r, h) = self.bounds();
        let by_overhead = if h == 0 { f64::INFINITY } else { level / h as f64 };
        level / self.cap() * r.min(by_overhead)
    }

    /// The level at which `ceiling` first exceeds `target`, or None if no
    /// level under `cap` does.
    pub fn level_for(self, target: f64) -> Option<f64> {
        let (r, h) = self.bounds();
        let cap = self.cap();
        let h = h as f64;
        // Below `r * h` the overhead term binds and the ceiling is quadratic
        // in level; above, the rate binds and it is linear.
        let u = if h == 0.0 {
            target * cap / r
        } else {
            let quad = (target * cap * h).sqrt();
            if quad <= r * h { quad } else { target * cap / r }
        };
        (u < cap).then_some(u)
    }
}

/// One need's standing with one resident.
#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[ts(export)]
pub struct Bucket {
    pub need: Need,
    /// Milliseconds of obligation owed.
    pub level: f64,
}

impl Bucket {
    /// A full set, the way a new resident is issued them.
    pub fn fresh() -> Vec<Bucket> {
        Need::ALL.iter().map(|&need| Bucket { need, level: need.initial() }).collect()
    }
}

/// A building's offer to serve one need.
#[derive(Debug, Clone)]
pub struct Tap {
    pub need: Need,
    pub curve: Curve,
    /// Obligation discharged per availability-millisecond. Infinite for a
    /// service whose length is fixed regardless of how much is owed.
    pub rate: f64,
    /// Time on arrival before service begins.
    pub overhead: GameTime,
}

/// What each kind of building serves. Fixed definitions, built once.
static TAPS: LazyLock<Vec<(BuildingKind, Vec<Tap>)>> = LazyLock::new(|| {
    let tap = |need, curve| Tap { need, curve, rate: 1.0, overhead: 0 };
    let work = |open: u32, close: u32| vec![tap(Need::Work, Curve::hours(open * H, close * H))];
    // Nobody sleeps at noon: sleep is on offer through the night. Being
    // home, and the kitchen, are on offer always.
    let home = || {
        vec![
            tap(Need::Rest, Curve::hours(22 * H, 7 * H)),
            tap(Need::Home, Curve::always()),
            tap(Need::Eat, Curve::always()),
        ]
    };
    // Staggered by kind so the city's rush hour is a wave rather than a
    // spike: industry starts before offices, offices before shops.
    vec![
        (BuildingKind::House, home()),
        (BuildingKind::Apartment, home()),
        (BuildingKind::Factory, work(6, 15)),
        (BuildingKind::Workshop, work(7, 16)),
        (BuildingKind::Office, work(8, 17)),
        (BuildingKind::Shop, [work(9, 18), vec![tap(Need::Eat, Curve::hours(9 * H, 18 * H))]].concat()),
    ]
});

pub fn taps(kind: BuildingKind) -> &'static [Tap] {
    TAPS.iter().find(|(k, _)| *k == kind).map_or(&[], |(_, t)| t.as_slice())
}

/// Build every curve and check the definitions against the invariants the
/// decision procedure leans on. Called once at startup, so nothing is
/// materialised lazily later and a bad table fails before anyone acts on it.
pub fn check() {
    let day = DAY_MS as u64;
    // N1: what accrues fits in a day.
    let asked: f64 = Need::ALL.iter().map(|n| n.daily_ms()).sum();
    assert!(asked <= day as f64, "needs ask for {:.1}h of a 24h day", asked / HOUR);

    for (kind, taps) in TAPS.iter() {
        for tap in taps {
            // T1: a fixed-length service still takes time.
            assert!(
                tap.rate.is_finite() || tap.overhead > 0,
                "{kind:?} serves {:?} instantly and for free",
                tap.need
            );
            // C1: a full bucket drains within the one-day horizon.
            assert!(
                tap.need.fill() == 0.0 || tap.need.cap() / tap.rate <= day as f64,
                "{kind:?} takes over a day to drain {:?}",
                tap.need
            );
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_definitions_hold_up() {
        check();
    }

    #[test]
    fn rest_asks_for_eight_hours() {
        assert!((Need::Rest.daily_ms() - 8.0 * HOUR).abs() < 1.0);
    }

    #[test]
    fn the_ceiling_inverts() {
        for need in Need::ALL {
            let level = 0.3 * need.cap();
            let target = need.ceiling(level);
            let back = need.level_for(target).expect("under cap");
            assert!((back - level).abs() < 1.0, "{need:?}: {back} vs {level}");
        }
        assert_eq!(Need::Rest.level_for(f64::INFINITY), None);
    }

    #[test]
    fn a_home_offers_sleep_and_a_shop_offers_work() {
        assert!(taps(BuildingKind::House).iter().any(|t| t.need == Need::Rest));
        assert!(taps(BuildingKind::Shop).iter().any(|t| t.need == Need::Work));
        assert!(taps(BuildingKind::House).iter().all(|t| t.need != Need::Work));
        assert!(taps(BuildingKind::Shop).iter().any(|t| t.need == Need::Eat));
    }
}
