pub mod curve;

use serde::{Deserialize, Serialize};
use ts_rs::TS;

use crate::engine::GameTime;
use crate::protocol::DAY_MS;
use curve::Curve;

const H: u32 = DAY_MS / 24;
const HOUR: f64 = H as f64;

/// Something a resident has to do. Three kinds, by where the timing lives:
/// an **accruing** need is generated by the passage of time and carries it
/// in `fill`; a **constant** need is imposed by the world and carries it in
/// the curve of whatever serves it, holding a fixed level meanwhile; a
/// **driven** need is generated by the road, a little per tile, and is the
/// car's rather than the day's.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, TS)]
#[ts(export)]
pub enum Need {
    /// Being at home. The baseline every other activity has to beat, and
    /// what pulls a resident back when the shift ends and nothing else is
    /// open yet.
    Home,
    Work,
    Rest,
    /// Meals take as long as the hunger owed, up to a sitting: served at
    /// home always, and wherever sells food while it is open.
    Eat,
    /// Time off. Served indifferently at home and well at a place to go —
    /// the first need with nothing in the world to say when.
    Leisure,
    /// The tank. Owed by the mile rather than the hour, and paid at a pump.
    Fuel,
}

impl Need {
    /// Baseline first, so ties fall to staying put.
    pub const ALL: [Need; 6] = [Need::Home, Need::Work, Need::Rest, Need::Eat, Need::Leisure, Need::Fuel];

    /// A tank's worth, in tiles. What sets how often anyone stops for fuel.
    pub const TANK_TILES: f64 = 500.0;

    /// Obligation per tile driven: a whole tank is a stop of twenty
    /// minutes, which is what it takes for the stop to be worth the detour.
    pub fn per_tile() -> f64 {
        Need::Fuel.cap() / Need::TANK_TILES
    }

    /// Holds its level: the world's curves say when, not the bucket.
    pub fn constant(self) -> bool {
        matches!(self, Need::Work | Need::Home)
    }

    /// Obligation gained per millisecond not spent on it. Zero for a
    /// constant need. For `D` hours a day at unit rate this is `D / (24 - D)`.
    pub fn fill(self) -> f64 {
        match self {
            Need::Work | Need::Home | Need::Fuel => 0.0,
            Need::Rest => 8.0 / 16.0,
            // About 1.2 hours a day, as people actually spend: a sitting is
            // owed ten hours after the last, and lunch out is worth the
            // drive about six hours after breakfast.
            Need::Eat => 0.05,
            // About five hours a day, as people actually spend, at the rate
            // home serves it.
            Need::Leisure => 0.35 * 5.0 / 19.0,
        }
    }

    /// The most obligation that can pile up, in milliseconds.
    pub fn cap(self) -> f64 {
        match self {
            Need::Work | Need::Home => 24.0 * HOUR,
            Need::Rest => 12.0 * HOUR,
            Need::Eat => 0.5 * HOUR,
            Need::Leisure => 5.0 * HOUR,
            Need::Fuel => HOUR / 3.0,
        }
    }

    /// Where a fresh bucket starts. A constant need sits at `k * cap` for
    /// good, and `k` is the threshold: the agent works unless something else
    /// is more than this full. Home must beat waiting overnight at work
    /// (`0.5 * shift / 24`, about 0.19) and lose to a morning's commute.
    pub fn initial(self) -> f64 {
        match self {
            Need::Work => 0.5 * self.cap(),
            Need::Home => 0.3 * self.cap(),
            Need::Rest | Need::Eat | Need::Leisure => 0.0,
            // Nobody arrives on empty, and nobody arrives having just filled up.
            Need::Fuel => 0.5 * self.cap(),
        }
    }

    /// Hours a day an accruing need asks for: the referent `fill` was
    /// derived from. Zero for a constant need, which fills time rather than
    /// demanding it.
    fn daily_ms(self) -> f64 {
        let fill = self.fill();
        DAY_MS as f64 * fill / (1.0 + fill)
    }

    /// The best any tap anywhere serves this: greatest rate, least overhead.
    /// What bounds a bucket's score without looking at any building.
    pub fn bounds(self) -> (f64, GameTime) {
        crate::blueprint::all_taps()
            .filter(|t| t.need == self)
            .fold((0.0, GameTime::MAX), |(r, h), t| (r.max(t.rate), h.min(t.overhead)))
    }

    /// The most any option for a bucket at `level` can score, from the
    /// bounds alone: `w * min(R, L / H)`.
    pub fn ceiling(self, level: f64) -> f64 {
        let (r, h) = self.bounds();
        let by_overhead = if h == 0 { f64::INFINITY } else { level / h as f64 };
        level / self.cap() * r.min(by_overhead)
    }

    /// The level at which `ceiling` first exceeds `target`, or None if no
    /// level under `cap` does.
    pub fn level_for(self, target: f64) -> Option<f64> {
        let (r, h) = self.bounds();
        let cap = self.cap();
        let h = h as f64;
        // Below `r * h` the overhead term binds and the ceiling is quadratic
        // in level; above, the rate binds and it is linear.
        let u = if h == 0.0 {
            target * cap / r
        } else {
            let quad = (target * cap * h).sqrt();
            if quad <= r * h { quad } else { target * cap / r }
        };
        (u < cap).then_some(u)
    }
}

/// One need's standing with one resident.
#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[ts(export)]
pub struct Bucket {
    pub need: Need,
    /// Milliseconds of obligation owed.
    pub level: f64,
}

impl Bucket {
    /// A full set, the way a new resident is issued them.
    pub fn fresh() -> Vec<Bucket> {
        Need::ALL.iter().map(|&need| Bucket { need, level: need.initial() }).collect()
    }

    /// Any need a saved resident predates, issued fresh.
    pub fn top_up(buckets: &mut Vec<Bucket>) {
        for &need in &Need::ALL {
            if !buckets.iter().any(|b| b.need == need) {
                buckets.push(Bucket { need, level: need.initial() });
            }
        }
    }
}

/// A building's offer to serve one need.
#[derive(Debug, Clone)]
pub struct Tap {
    pub need: Need,
    pub curve: Curve,
    /// Obligation discharged per availability-millisecond. Infinite for a
    /// service whose length is fixed regardless of how much is owed.
    pub rate: f64,
    /// Time on arrival before service begins.
    pub overhead: GameTime,
    /// How many it serves at once at full rate. Past that, everyone present
    /// is served proportionally slower.
    pub slots: u32,
}

/// Check the needs against the invariant the decision procedure leans on.
/// What each building serves is checked with its blueprint.
pub fn check() {
    let day = DAY_MS as u64;
    // N1: what accrues fits in a day.
    let asked: f64 = Need::ALL.iter().map(|n| n.daily_ms()).sum();
    assert!(asked <= day as f64, "needs ask for {:.1}h of a 24h day", asked / HOUR);
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_definitions_hold_up() {
        check();
    }

    #[test]
    fn rest_asks_for_eight_hours() {
        assert!((Need::Rest.daily_ms() - 8.0 * HOUR).abs() < 1.0);
    }

    #[test]
    fn the_ceiling_inverts() {
        for need in Need::ALL {
            let level = 0.3 * need.cap();
            let target = need.ceiling(level);
            let back = need.level_for(target).expect("under cap");
            assert!((back - level).abs() < 1.0, "{need:?}: {back} vs {level}");
        }
        assert_eq!(Need::Rest.level_for(f64::INFINITY), None);
    }
}
