pub mod curve;

use std::sync::LazyLock;

use serde::{Deserialize, Serialize};
use ts_rs::TS;

use crate::engine::GameTime;
use crate::protocol::{BuildingKind, DAY_MS};
use curve::Curve;

const H: u32 = DAY_MS / 24;
const HOUR: f64 = H as f64;

/// Something a resident has to do. Two kinds, by where the timing lives:
/// an **accruing** need is generated by the passage of time and carries it
/// in `fill`; a **constant** need is imposed by the world and carries it in
/// the curve of whatever serves it, holding a fixed level meanwhile.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, TS)]
#[ts(export)]
pub enum Need {
    Work,
    Rest,
}

impl Need {
    pub const ALL: [Need; 2] = [Need::Work, Need::Rest];

    /// Obligation gained per millisecond not spent on it. Zero for a
    /// constant need. For `D` hours a day at unit rate this is `D / (24 - D)`.
    pub fn fill(self) -> f64 {
        match self {
            Need::Work => 0.0,
            Need::Rest => 8.0 / 16.0,
        }
    }

    /// The most obligation that can pile up, in milliseconds.
    pub fn cap(self) -> f64 {
        match self {
            Need::Work => 24.0 * HOUR,
            Need::Rest => 12.0 * HOUR,
        }
    }

    /// Where a fresh bucket starts. A constant need sits at `k * cap` for
    /// good, and `k` is the threshold: the agent works unless something else
    /// is more than this full.
    pub fn initial(self) -> f64 {
        match self {
            Need::Work => 0.5 * self.cap(),
            Need::Rest => 0.0,
        }
    }

    /// Hours a day this asks for, the referent `fill` was derived from.
    /// For a constant need it is the longest any tap serves it.
    fn daily_ms(self) -> f64 {
        let fill = self.fill();
        if fill > 0.0 {
            return DAY_MS as f64 * fill / (1.0 + fill);
        }
        TAPS.iter()
            .flat_map(|(_, taps)| taps.iter())
            .filter(|t| t.need == self)
            .map(|t| t.curve.integral(0, DAY_MS as u64))
            .fold(0.0, f64::max)
    }
}

/// One need's standing with one resident.
#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[ts(export)]
pub struct Bucket {
    pub need: Need,
    /// Milliseconds of obligation owed.
    pub level: f64,
}

impl Bucket {
    /// A full set, the way a new resident is issued them.
    pub fn fresh() -> Vec<Bucket> {
        Need::ALL.iter().map(|&need| Bucket { need, level: need.initial() }).collect()
    }
}

/// A building's offer to serve one need.
#[derive(Debug, Clone)]
pub struct Tap {
    pub need: Need,
    pub curve: Curve,
    /// Obligation discharged per availability-millisecond. Infinite for a
    /// service whose length is fixed regardless of how much is owed.
    pub rate: f64,
    /// Time on arrival before service begins.
    pub overhead: GameTime,
}

/// What each kind of building serves. Fixed definitions, built once.
static TAPS: LazyLock<Vec<(BuildingKind, Vec<Tap>)>> = LazyLock::new(|| {
    let work = |open: u32, close: u32| {
        vec![Tap { need: Need::Work, curve: Curve::hours(open * H, close * H), rate: 1.0, overhead: 0 }]
    };
    // Nobody sleeps at noon. Sleep is on offer through the night, and it is
    // the one thing a home offers so far.
    let home = || {
        vec![Tap { need: Need::Rest, curve: Curve::hours(22 * H, 7 * H), rate: 1.0, overhead: 0 }]
    };
    // Staggered by kind so the city's rush hour is a wave rather than a
    // spike: industry starts before offices, offices before shops.
    vec![
        (BuildingKind::House, home()),
        (BuildingKind::Apartment, home()),
        (BuildingKind::Factory, work(6, 15)),
        (BuildingKind::Workshop, work(7, 16)),
        (BuildingKind::Office, work(8, 17)),
        (BuildingKind::Shop, work(9, 18)),
    ]
});

pub fn taps(kind: BuildingKind) -> &'static [Tap] {
    TAPS.iter().find(|(k, _)| *k == kind).map_or(&[], |(_, t)| t.as_slice())
}

/// Build every curve and check the definitions against the invariants the
/// decision procedure leans on. Called once at startup, so nothing is
/// materialised lazily later and a bad table fails before anyone acts on it.
pub fn check() {
    let day = DAY_MS as u64;
    // N1: the needs fit in a day.
    let asked: f64 = Need::ALL.iter().map(|n| n.daily_ms()).sum();
    assert!(asked <= day as f64, "needs ask for {:.1}h of a 24h day", asked / HOUR);

    for (kind, taps) in TAPS.iter() {
        for tap in taps {
            // T1: a fixed-length service still takes time.
            assert!(
                tap.rate.is_finite() || tap.overhead > 0,
                "{kind:?} serves {:?} instantly and for free",
                tap.need
            );
            // C1: no visit outlasts the one-day horizon.
            if tap.need.fill() > 0.0 {
                assert!(
                    tap.need.cap() / tap.rate <= day as f64,
                    "{kind:?} takes over a day to drain {:?}",
                    tap.need
                );
            } else {
                assert!(
                    tap.curve.next_zero(0) < day || tap.curve.at(0) == 0.0,
                    "{kind:?} never closes, and {:?} never runs out",
                    tap.need
                );
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_definitions_hold_up() {
        check();
    }

    #[test]
    fn rest_asks_for_eight_hours() {
        assert!((Need::Rest.daily_ms() - 8.0 * HOUR).abs() < 1.0);
    }

    #[test]
    fn a_home_offers_sleep_and_a_shop_offers_work() {
        assert!(taps(BuildingKind::House).iter().any(|t| t.need == Need::Rest));
        assert!(taps(BuildingKind::Shop).iter().any(|t| t.need == Need::Work));
        assert!(taps(BuildingKind::House).iter().all(|t| t.need != Need::Work));
    }
}
