// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Need } from "./Need";

/**
 * One need's standing with one resident.
 */
export type Bucket = { need: Need, 
/**
 * Milliseconds of obligation owed.
 */
level: number, };
