// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Need } from "./Need";

/**
 * One need's standing with one resident.
 */
export type Bucket = { need: Need, 
/**
 * Milliseconds of obligation owed.
 */
level: number, 
/**
 * How far short of being served on the spot the last wake fell, from 0
 * (as well as it could be) to 1 (nothing found anywhere). A record of
 * the last decision, not a plan: the demand readout sums it to say what
 * the city wants and where, without asking anyone to think again.
 */
shortfall: number, };
