// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildingKind } from "./BuildingKind";
import type { Door } from "./Door";
import type { GridCoord } from "./GridCoord";
import type { Need } from "./Need";
import type { Stock } from "./Stock";
import type { Tile } from "./Tile";

export type Building = { kind: BuildingKind, 
/**
 * The tiles it stands on, its lot's among them; the first is where it
 * is, the tile it is known by.
 */
tiles: Array<GridCoord>, 
/**
 * Which side of the building the lot and the street are on; see
 * `blueprint::FACINGS`. The client lays the building and the lot out
 * within the footprint from this.
 */
facing: number, 
/**
 * Its stocks, by good: the shelf of what it serves or keeps — meals,
 * tanks, a farm's crates — drawn down by visits and loads and filled
 * by a delivery or its own land. Empty shelves serve nothing. A save
 * from before a stock existed gets it issued at load
 * (`economy::open`).
 */
stocks: { [key in Need]?: Stock }, 
/**
 * A farm's land: the grass it claimed when a street reached it, each
 * tile at a stage of the cycle the tractor drives it through
 * (`world/fields.rs`). A tile built over is dropped.
 */
land: Array<Tile>, 
/**
 * Where the tractor last drove: one run's path, which the client
 * draws the field along, corners and all. Every run works the same
 * ground, so the last run's path is the field. Redrawn by the next.
 */
ruts: Array<GridCoord>, 
/**
 * The tiles beside it, of other buildings of its kind, the hand drew
 * it on from or onto: a row of houses drawn as a row, each a home of
 * its own. Only a kind that never grows into one building keeps any.
 */
joined: Array<GridCoord>, 
/**
 * Where it is driven into: one of its tiles, and the street tile
 * beside it the drive runs from. The drive is the building's, not a
 * road: drawn as one, driven by the cars of its lot, and gone with it.
 * Kept when the street goes, and good again if it comes back.
 */
door: Door | null, };
