// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildingKind } from "./BuildingKind";
import type { Need } from "./Need";
import type { Stock } from "./Stock";

export type Building = { kind: BuildingKind, 
/**
 * The plot's footprint in tiles, as it lies on the grid: the building
 * and its lot together.
 */
size: [number, number], 
/**
 * Which side of the building the lot and the street are on; see
 * `blueprint::FACINGS`. The client lays the building and the lot out
 * within the footprint from this.
 */
facing: number, 
/**
 * What is on the shelves, in units of what it sells: meals, tanks.
 * Drawn down by sales, filled by a delivery; empty shelves sell
 * nothing. Cap zero for a kind that keeps no stock. A save from
 * before shelves were a stock gets one issued at load.
 */
stock: Stock, 
/**
 * The price posted on each thing it sells, per unit of the need.
 * Nudged daily by its own stock, never below unit cost. Issued at the
 * edge's price to a save from before prices.
 */
prices: { [key in Need]?: number }, };
