// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildingKind } from "./BuildingKind";

export type Building = { kind: BuildingKind, 
/**
 * Footprint in tiles, as it lies on the grid.
 */
size: [number, number], 
/**
 * What is on the shelves, as a fraction of a delivery. Drawn down by
 * visits, filled by a delivery; empty shelves sell nothing. Always
 * full for a kind that keeps no stock.
 */
stock: number, };
