// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a call is for, and so who answers it.
 */
export type CallKind = "Stock" | "Fetch";
