// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CarRole } from "./CarRole";
import type { Pose } from "./Pose";
import type { Trip } from "./Trip";

/**
 * Someone's car. It outlives its journeys: between trips it sits parked at a
 * building, doing nothing and costing nothing, and everything about the
 * journey it is currently on lives in `trip`.
 */
export type Car = { 
/**
 * Who it belongs to: the resident driving it, whose `at` points back
 * at this car while they are aboard; or the facility it works for; or,
 * come from beyond the edge, the building that called it.
 */
owner: number, trip: Trip | null, role: CarRole, 
/**
 * Where it stands while parked, if the lot had room: the spot's centre
 * and the way its nose points, in radians. `None` is parked out of
 * sight.
 */
spot: Pose | null, };
