// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChunkBounds = { min_cx: number, min_cy: number, max_cx: number, max_cy: number, };
