// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which of the tree's three avenues a kind belongs to. Taking one makes
 * its class cheaper to place; nothing else reads this.
 */
export type Class = "Living" | "Commerce" | "Industry";
