// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What company a kind keeps. Homes flock, commerce goes where the homes
 * are, industry keeps to itself — the spawner's whole sense of neighbourhood.
 */
export type Class = "Living" | "Commerce" | "Industry";
