// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Build } from "./Build";
import type { Cell } from "./Cell";
import type { ChunkBounds } from "./ChunkBounds";

export type ClientMessage = { "type": "Build", "data": Build } | { "type": "Take", "data": Cell } | { "type": "DespawnAllCars" } | { "type": "SetSpeed", "data": number } | { "type": "ResetWorld" } | { "type": "SetChunks", "data": ChunkBounds } | { "type": "Ping" };
