// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Cell } from "./Cell";
import type { ChunkBounds } from "./ChunkBounds";
import type { DemolishRoad } from "./DemolishRoad";
import type { PlaceBuilding } from "./PlaceBuilding";
import type { PlaceRoad } from "./PlaceRoad";

export type ClientMessage = { "type": "PlaceRoad", "data": PlaceRoad } | { "type": "Take", "data": Cell } | { "type": "PlaceBuilding", "data": PlaceBuilding } | { "type": "DemolishRoad", "data": DemolishRoad } | { "type": "DespawnAllCars" } | { "type": "SetSpeed", "data": number } | { "type": "ResetWorld" } | { "type": "SetChunks", "data": ChunkBounds } | { "type": "Ping" };
