// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The simulation's clock, as the client needs to see it.
 *
 * `speed` is how many 10ms steps the server runs per tick, so it is also the
 * rate sim time advances relative to wall time — the client extrapolates car
 * positions with it between updates.
 */
export type Clock = { now: number, speed: number, day_ms: number, };
