// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GridCoord } from "./GridCoord";

/**
 * A building's door: its tile a drive runs onto, and the street tile the
 * drive runs from.
 */
export type Door = { tile: GridCoord, street: GridCoord, };
