// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An uncommitted change, and whose it is.
 *
 * A draft is an ordinary world object that reserves its space and is visible
 * to everyone, but is invisible to traffic and to persistence. Two questions
 * get different answers: the planner and the renderer see the world as it will
 * be after commit, while traffic sees it as it is now. So an `Added` road
 * carries no cars but does block a plot, and a `Removed` road still carries
 * cars but will not be given a new driveway.
 */
export type Draft = { "state": "Added", "owner": number } | { "state": "Removed", "owner": number };
