// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildingKind } from "./BuildingKind";
import type { Class } from "./Class";

/**
 * What taking a node does. Odds and unlocks only; no verbs.
 */
export type Effect = { "kind": "Nothing" } | { "kind": "Weight", "data": { class: Class, times: number, } } | { "kind": "Building", "data": BuildingKind } | { "kind": "OneWay" } | { "kind": "RoadTiles", "data": number };
