// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GridCoord } from "./GridCoord";

/**
 * A tile of a farm's land, and when its crop is ripe: a day after the
 * tractor last took it, and at once for a field just claimed.
 */
export type Field = { at: GridCoord, ripe: number, };
