// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A good: what a shelf, a yard or a box holds, and what the world
 * prices. A resident's need draws one off a counter's shelf (`Need::good`).
 */
export type Good = "Crates" | "Fuel" | "Timber" | "Stone";
