// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Cell } from "./Cell";

/**
 * How the city is doing, as the two dials read it.
 *
 * The level is the town's GDP to date.
 * The treasury is the mayor's coins, stepped as goods cross the border.
 * Neither is extrapolated: a dial that steps is the event landing.
 */
export type Growth = { level: number, 
/**
 * GDP since the level was reached, and what the next takes.
 */
toward: number, needed: number, 
/**
 * GDP added in town today so far.
 */
gdp: number, 
/**
 * What the town has to spend, in coins: earned at the border, net of
 * what it bought and built.
 */
treasury: number, 
/**
 * Today's net at the border so far, and what went out: the treasury
 * over it is days of imports left.
 */
income: number, imports: number, 
/**
 * The build: the nodes of the tree taken.
 */
taken: Array<Cell>, 
/**
 * Tiles of road the mayor may still lay.
 */
road_tiles_left: number, };
