// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a box is on its way, as the shipments list reads it.
 */
export type Leg = "Booked" | "Aboard" | "Parked" | "Hauled" | "Yard";
