// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Something landing on a building: coins as goods cross the border, a
 * load sold to the world or a delivery bought from it, negative leaving;
 * or GDP as value is added there, a meal served, a crop cut, a shift
 * worked at a desk. docs/trade.md.
 */
export type Lump = { building: number, coins: number, gdp: number, at: number, };
