// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Build } from "./Build";

/**
 * A step of the hand, drafted.
 */
export type Mark = { step: Build, 
/**
 * Refused at the last commit: something else stands there now, or it
 * reaches nothing.
 */
stuck: boolean, };
