// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Something a resident has to do, and so a good: what a tap serves, what
 * a shelf holds, what a price is per unit of. Three kinds, by where the
 * timing lives: a **timed** need is used up by the passage of time and
 * carries it in `drain`; a **constant** need is imposed by the world and
 * carries it in the curve of whatever serves it, holding a fixed level
 * meanwhile; a **driven** need is used up by the road, a little per tile,
 * and is the car's rather than the day's. And one is a building's alone:
 * **services**, drawn by the day of operation and delivered by a call.
 */
export type Need = "Home" | "Work" | "Rest" | "Eat" | "Leisure" | "Fuel" | "Services";
