// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a node is.
 */
export type NodeKind = "Root" | "Homes" | "Apartments" | "Shops" | "Restaurant" | "Bar" | "GasStation" | "Industry" | "Workshop" | "Factory" | "Roads" | "OneWay";
