// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameObjectEntry } from "./GameObjectEntry";

export type Operation = { "op": "Upsert", "data": GameObjectEntry } | { "op": "Delete", "data": number };
