// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildingType } from "./BuildingType";
import type { GridCoord } from "./GridCoord";

export type PlaceBuilding = { pos: GridCoord, building_type: BuildingType, };
