// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GridCoord } from "./GridCoord";

export type PlaceRoad = { from: GridCoord, to: GridCoord, one_way: boolean, 
/**
 * A road rather than a street: a through route nothing fronts onto.
 */
road: boolean, };
