// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildingKind } from "./BuildingKind";
import type { GridCoord } from "./GridCoord";

export type PlaceBuilding = { pos: GridCoord, kind: BuildingKind, };
