// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildingKind } from "./BuildingKind";

export type PlaceBuilding = { 
/**
 * The point on the ground the building is held over: the server
 * decides where the plot lands from it, the same way it showed the
 * mayor while dragging.
 */
at: [number, number], kind: BuildingKind, };
