// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Bucket } from "./Bucket";
import type { Need } from "./Need";

/**
 * Someone who lives in the city, and the two buildings their day runs between.
 *
 * Deliberately position-less: a resident is not a thing on the map but the
 * reason a car exists. `flush_dirty` only streams entities that have a
 * position, so residents persist and stay entirely server-side for free.
 */
export type Resident = { home: number, 
/**
 * `None` while nowhere within reach has a job going.
 */
work: number | null, 
/**
 * Where they are: a building, or the car they are riding in. `None` is
 * off-map — someone who exists but has not driven in yet.
 */
at: number | null, 
/**
 * The car they own. Settled alongside homes and jobs; defaults so saves
 * from before cars were owned settle themselves a car on load.
 */
car: number, 
/**
 * What they owe each need. Issued fresh to anyone saved before needs
 * existed.
 */
buckets: Array<Bucket>, 
/**
 * The need being served where they stand, if any. A record of what is
 * happening, like `at` — not a plan.
 */
selected: Need | null, 
/**
 * When the buckets were last brought up to date.
 */
last_update: number, 
/**
 * Their purse, in hours of the edge's wage. A shift pays into it, a
 * meal or a tank is paid from it, and what is over the float sweeps
 * to the treasury as rent. docs/economy.md §3, §8.2.
 */
wallet: number, 
/**
 * Units of the selected need served since this visit began, not yet
 * paid for: the sale lands as one lump when the visit ends. A record
 * of what is happening, like `at`.
 */
tab: number, };
