// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Effect } from "./Effect";

export type Row = { name: string, effect: Effect, 
/**
 * Points to take it.
 */
cost: number, 
/**
 * What the player learns by taking it: what the thing does.
 */
blurb: string, };
