// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GridCoord } from "./GridCoord";
import type { Job } from "./Job";

/**
 * A tractor's run over the land: the tiles it drives in order, doing its
 * job to each as it arrives, standing on the first at `started` and
 * reaching one more every `pace` milliseconds. Off the roads: no route,
 * no claims, no queue — and nothing that changes as it goes, so the
 * run is sent once.
 */
export type Run = { job: Job, path: Array<GridCoord>, started: number, pace: number, };
