// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A harbour's ferry, as its timetable reads.
 */
export type Sailing = { harbour: number, ferry: number, 
/**
 * When it next berths, or berthed; and when it casts off.
 */
arrives: number, departs: number, 
/**
 * At the ramp now.
 */
berthed: boolean, 
/**
 * Boxes and settlers aboard, and how many the deck holds.
 */
boxes: number, settlers: number, deck: number, 
/**
 * Boxes booked beyond the sea for this harbour.
 */
booked: number, 
/**
 * Households moved in and waiting beyond the sea for a sailing.
 */
waiting: number, };
