// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Coins landing somewhere on the map as goods cross the border: a load
 * sold to the world, a delivery or a tank bought from it. Negative is
 * coins leaving. docs/trade.md, Coins.
 */
export type Sale = { building: number, amount: number, at: number, };
