// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChunkCoord } from "./ChunkCoord";
import type { ErrorMessage } from "./ErrorMessage";
import type { StateUpdate } from "./StateUpdate";
import type { TerrainChunk } from "./TerrainChunk";

export type ServerMessage = { "type": "Update", "data": StateUpdate } | { "type": "TerrainChunk", "data": TerrainChunk } | { "type": "UnloadChunk", "data": ChunkCoord } | { "type": "Error", "data": ErrorMessage } | { "type": "Pong", "data": number };
