// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Pose } from "./Pose";
import type { Trailer } from "./Trailer";

/**
 * A dock of a harbour's trailer park: where a box stands in it, a
 * lorry's tail to the quay, and the box, if one is there.
 */
export type Slot = { pose: Pose, trailer: Trailer | null, };
