// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChunkBounds } from "./ChunkBounds";
import type { Clock } from "./Clock";
import type { Draft } from "./Draft";
import type { Growth } from "./Growth";
import type { Lump } from "./Lump";
import type { Operation } from "./Operation";
import type { Sea } from "./Sea";

export type StateUpdate = { ops: Array<Operation>, 
/**
 * Lumps that landed on buildings in view since the last update.
 */
lumps: Array<Lump>, clock: Clock, growth: Growth, 
/**
 * Every shipment on its way and every harbour's timetable.
 */
sea: Sea, 
/**
 * Every player's draft and its bill.
 */
drafts: Array<Draft>, terrain_seed: number, 
/**
 * The island's map, which the client keeps its camera inside.
 */
island: ChunkBounds, };
