// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChunkBounds } from "./ChunkBounds";
import type { Clock } from "./Clock";
import type { Growth } from "./Growth";
import type { Lump } from "./Lump";
import type { Operation } from "./Operation";

export type StateUpdate = { ops: Array<Operation>, 
/**
 * Lumps that landed on buildings in view since the last update.
 */
lumps: Array<Lump>, clock: Clock, growth: Growth, terrain_seed: number, 
/**
 * Extent of the surveyed world, which the client keeps its camera inside.
 */
revealed_bounds: ChunkBounds, };
