// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TerrainType } from "./TerrainType";

export type TerrainTile = { terrain_type: TerrainType, 
/**
 * Corner overlays: [BL, BR, TR, TL]. Each is Some(type) when both
 * cardinal neighbors at that corner share a type different from this cell.
 */
corners: Array<TerrainType | null>, 
/**
 * 2 bits per corner encoding edge connectivity.
 * For corner i: bits (i*2) = edge A continues, (i*2+1) = edge B continues.
 */
corner_mask: number, 
/**
 * Cardinal edges: [bottom, right, top, left].
 * Some(type) when this tile has exactly 1 differing neighbor, or 2 on opposing sides.
 */
edges: Array<TerrainType | null>, };
