// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TerrainType = "Water" | "Water2" | "Water3" | "Grass" | "Forest" | "Mountain";
