// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChunkCoord } from "./ChunkCoord";

/**
 * Terrain is static, so it travels as a block of tile types rather than as
 * entities. The payload carries CHUNK_SKIRT tiles of margin on every side:
 * the client derives corner shapes from surrounding types, reaching up to
 * two tiles past the one it is drawing.
 */
export type TerrainChunk = { coord: ChunkCoord, 
/**
 * CHUNK_STRIDE^2 bytes, row-major from the chunk origin minus the skirt.
 */
tiles: Uint8Array, };
