// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChunkCoord } from "./ChunkCoord";

/**
 * Terrain is static, so it travels as a block of tile types rather than as
 * entities. The payload carries CHUNK_SKIRT tiles of margin on every side:
 * the client derives corner shapes from surrounding types, reaching up to
 * two tiles past the one it is drawing.
 */
export type TerrainChunk = { coord: ChunkCoord, 
/**
 * CHUNK_STRIDE^2 bytes, row-major from the chunk origin minus the skirt.
 */
tiles: Uint8Array, 
/**
 * The mountains' heights over the chunk and a tile round it, eroded
 * (`mountains.rs`): `mountains::SIDE` by `SIDE` points, `SAMPLES` to
 * a tile, a row of x at a time from a tile short of its corner, each
 * two bytes, low first, in `UNIT`s of a tile. Empty off the mountains.
 */
heights: Uint8Array, };
