// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GridCoord } from "./GridCoord";
import type { Stage } from "./Stage";

/**
 * A tile of a farm's land, and where it is in the cycle: grass until the
 * tractor ploughs it, bare until it seeds it, growing from `since` until a
 * day on, cut after the harvest, and ploughed again.
 */
export type Tile = { at: GridCoord, stage: Stage, since: number, };
