// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Good } from "./Good";

/**
 * A box: a trailer off the ferry, the world's, which the town's lorries
 * haul. Never an entity: a value that stands in one place at a time, on
 * a ferry's deck, in a yard's slot, on a hitch, or booked beyond the sea
 * (`World::booked`). docs/shipping.md §Boxes and lorries.
 */
export type Trailer = { 
/**
 * Its number, for following it wherever it is.
 */
id: number, 
/**
 * What is in it; None, or no units, is an empty.
 */
good: Good | null, units: number, 
/**
 * The depot it is bound for; None is the town's, for whichever depot's
 * lorry comes first, or the world's, going back.
 */
to: number | null, 
/**
 * Going out: dropped at a harbour for the ferry, an export or an empty.
 */
outbound: boolean, 
/**
 * The shipment it is part of: an order, a top-up, the starter pack.
 */
order: number | null, };
